name: daryo_uz_clone
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^5.1.0
  get: ^4.6.6
  flutter_svg: ^2.0.7
  cupertino_icons: ^1.0.6
  dio: ^5.3.2
  path_provider: ^2.1.1
  shared_preferences: ^2.2.1
  shimmer: ^3.0.0
  provider: ^6.0.5
  flutter_bloc: ^8.1.3
  #  yandex_mapkit: ^3.3.3
  #  geolocator: ^10.0.1
  #  geocoding: ^2.1.0
  cached_network_image: ^3.2.3
  firebase_core: ^2.15.1
  url_launcher: ^6.1.14
  flutter_share:
  firebase_auth: ^4.9.0
  pinput: ^3.0.1
  fluttertoast: ^8.2.2
  get_it: ^7.6.4
  floor: ^1.4.2
  maps_launcher: ^2.2.0
  flutter_holo_date_picker: ^1.1.0
  #  flutter_datetime_picker: ^1.3.5
  flutter_native_splash: ^2.3.2
  flutter_launcher_icons: ^0.13.1
  easy_localization: ^3.0.3

#flutter_native_splash:
#  color: "#323232"
#  image: assets/images/icons/beepul_logo.png
#
#flutter_icons:
#  android: "launcher_icon"
#  ios: true
#  image_path: "assets/images/icons/beepul_logo.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/bottom_nav_bar/
    - assets/images/icons/
    - assets/images/
